### ISSUE TITLE
[Roadmap] K-means algorithm is not implemented in 0.7 Release

### ISSUE THREAD

**Issue by rpovelik** [rapidsai/dask-cuml#53]
Hi,

I found Dask-CuML RoadMap which was presented on [GTC](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9817-rapids-cuml-a-library-for-gpu-accelerated-machine-learning.pdf), slide 60.

It is said that K-Means will be available in 0.7 release. I checked the package content and it does not contain the K-Means:

> $ print(dask_cuml.\_\_all\_\_)
> ['linear_model', 'neighbors', 'core']

My cuml version:

> $ conda list | grep cuml
> cuml                      0.7.0            cuda9.2_py36_0    rapidsai
> dask-cuml                 0.7.0                    py36_0    rapidsai
> libcuml                   0.7.0                 cuda9.2_0    rapidsai

Could you please provide some information regarding this component?

The slide screenshot:
![image](https://user-images.githubusercontent.com/20692004/60191844-a2025680-983d-11e9-8382-1277c828f093.png)

**Comment by cjnolet** [comment]
The orange blocks you see in the slide above denote that a feature is in-progress. The green denotes features that were currently available at the time the presentation was given.

It is looking like k-means MG and MNMG could be included in our next release, but I'll caveat that by stating that our delivery process is rather lean at the moment. 

We are also in the process of merging dask-cuml into the cuml repository, so this repository will likely not be undergoing any further releases after 0.8.

You can get up to date status info for our 0.9 release on the cuml [project board](https://github.com/rapidsai/cuml/projects/8).

**Comment by rpovelik** [comment]
@cjnolet thank you for your quick response!

> We are also in the process of merging dask-cuml into the cuml repository, so this repository will likely not be undergoing any further releases after 0.8.

Does it mean that dask-cuml KMeans implementation will be underneath the cuml KMeans call when the n_gpuint is not 1?

In documentation it is mentioned that exactly this part is under development:
> Number of GPUs to use. Currently uses single GPU, but will support multiple GPUs later.

**Comment by cjnolet** [comment]
> Does it mean that dask-cuml KMeans implementation will be underneath the cuml KMeans call when the n_gpuint is not 1?

We are still working through the exact details for this, but it is looking likely that this will be the case. Relevant discussion is in cuml issue [#750](https://github.com/rapidsai/cuml/issues/750). Feedback on that issue is much appreciated. 

Pre 0.7, Our kmeans used an implementation from h20gpu, which enabled multi-gpu. The kmeans introduced in 0.7 is only single-gpu.

**Comment by rpovelik** [comment]
@cjnolet, thank you a lot for the information!
